name: example
description: Example usage of the gulf_currency package.
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gulf_currency:
    path: ../
